version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=nico
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
volumes:
  postgresql-volume:
    external: true